-- Optional Supabase mirror. Local SQLite remains canonical.
create extension if not exists vector;
create extension if not exists pgmq;
create table if not exists public.alinacoder_memory_mirror (
 id bigint generated by default as identity primary key,
 tenant_id text not null,
 project_id text not null,
 kind text not null,
 lexical_text text not null default '',
 embedding vector(384),
 payload jsonb not null default '{}'::jsonb,
 source_hash text not null,
 created_at timestamptz not null default now()
);
alter table public.alinacoder_memory_mirror enable row level security;
create policy "project scoped mirror read" on public.alinacoder_memory_mirror for select using (tenant_id = current_setting('request.jwt.claims', true)::jsonb ->> 'tenant_id' and project_id = current_setting('request.jwt.claims', true)::jsonb ->> 'project_id');
create policy "project scoped mirror write" on public.alinacoder_memory_mirror for insert with check (tenant_id = current_setting('request.jwt.claims', true)::jsonb ->> 'tenant_id' and project_id = current_setting('request.jwt.claims', true)::jsonb ->> 'project_id');
create index if not exists alinacoder_memory_fts_idx on public.alinacoder_memory_mirror using gin (to_tsvector('simple', lexical_text));
-- PGMQ is at-least-once; AlinaCoder invocation id + fencing remains authoritative.
select pgmq.create('alinacoder_optional_coordination');
