-- Optional Supabase mirror. Local SQLite remains canonical and must keep working when this migration is absent or Supabase is unavailable.
create extension if not exists vector;
create extension if not exists pgmq;

create table if not exists public.alinacoder_memory_mirror (
 id bigint generated by default as identity primary key,
 tenant_id text not null,
 project_id text not null,
 kind text not null,
 lexical_text text not null default '',
 embedding vector(384),
 payload jsonb not null default '{}'::jsonb,
 source_hash text not null,
 created_at timestamptz not null default now()
);

alter table public.alinacoder_memory_mirror enable row level security;

drop policy if exists "project scoped mirror read" on public.alinacoder_memory_mirror;
drop policy if exists "project scoped mirror write" on public.alinacoder_memory_mirror;
drop policy if exists "project scoped mirror update" on public.alinacoder_memory_mirror;
drop policy if exists "project scoped mirror delete" on public.alinacoder_memory_mirror;

-- Authorization data is taken from immutable app_metadata rather than user-editable metadata.
create policy "project scoped mirror read"
on public.alinacoder_memory_mirror
for select
to authenticated
using (
 tenant_id = (select auth.jwt() -> 'app_metadata' ->> 'tenant_id')
 and project_id = (select auth.jwt() -> 'app_metadata' ->> 'project_id')
);

create policy "project scoped mirror write"
on public.alinacoder_memory_mirror
for insert
to authenticated
with check (
 tenant_id = (select auth.jwt() -> 'app_metadata' ->> 'tenant_id')
 and project_id = (select auth.jwt() -> 'app_metadata' ->> 'project_id')
);

create policy "project scoped mirror update"
on public.alinacoder_memory_mirror
for update
to authenticated
using (
 tenant_id = (select auth.jwt() -> 'app_metadata' ->> 'tenant_id')
 and project_id = (select auth.jwt() -> 'app_metadata' ->> 'project_id')
)
with check (
 tenant_id = (select auth.jwt() -> 'app_metadata' ->> 'tenant_id')
 and project_id = (select auth.jwt() -> 'app_metadata' ->> 'project_id')
);

create policy "project scoped mirror delete"
on public.alinacoder_memory_mirror
for delete
to authenticated
using (
 tenant_id = (select auth.jwt() -> 'app_metadata' ->> 'tenant_id')
 and project_id = (select auth.jwt() -> 'app_metadata' ->> 'project_id')
);

create index if not exists alinacoder_memory_scope_idx
on public.alinacoder_memory_mirror (tenant_id, project_id, created_at desc);

create index if not exists alinacoder_memory_fts_idx
on public.alinacoder_memory_mirror
using gin (to_tsvector('simple', lexical_text));

-- PGMQ is at-least-once. AlinaCoder's invocation id, idempotency ledger and fencing token remain authoritative.
-- Queue delivery is therefore coordination evidence only; it can never be the sole source of effect truth.
select pgmq.create('alinacoder_optional_coordination');
